const express = require('express');
const usuariosController = require('../controllers/usuarioController.js');
const router = express.Router();
router.get('/clientes', usuariosController.getAllclientes);
router.get('/empleados', usuariosController.getAllempleados);
router.get('/administradores', usuariosController.getAllAdministradores);
router.get("/clienteLogin", usuariosController.login);
router.put("/actualizarCliente/:idUsuario", usuariosController.actualizarCliente);
router.post("/crearCliente", usuariosController.crearCliente);
module.exports = router;
